"""change-relation-ship

Revision ID: 0dcd3acf382f
Revises: adb437cb796b
Create Date: 2025-12-12 15:23:06.136110

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0dcd3acf382f'
down_revision = 'adb437cb796b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
