"""migration-chag

Revision ID: 792708ed624f
Revises: ebf4b66990a5
Create Date: 2025-12-12 16:04:30.397740

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '792708ed624f'
down_revision = 'ebf4b66990a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otp_user_id'), table_name='otp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_otp_user_id'), 'otp', ['user_id'], unique=False)
    # ### end Alembic commands ###
