"""update user adn opt tale

Revision ID: c09c4a1bfec5
Revises: 8f75a59e9165
Create Date: 2025-12-18 11:55:26.319177

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c09c4a1bfec5'
down_revision = '8f75a59e9165'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum types first (Postgres requires the type to exist before using it)
    email_token_status = sa.Enum('active', 'used', 'expired', name='emailtokenstatus')
    user_status = sa.Enum('active', 'inactive', 'banned', name='userstatus')
    email_token_status.create(op.get_bind(), checkfirst=True)
    user_status.create(op.get_bind(), checkfirst=True)

    op.add_column('otp', sa.Column('email_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('otp', sa.Column('token_status', email_token_status, nullable=False))
    op.create_index(op.f('ix_otp_email_token'), 'otp', ['email_token'], unique=True)
    op.drop_column('otp', 'code')
    op.drop_column('otp', 'type')
    op.drop_column('otp', 'expires_at')
    op.add_column('user', sa.Column('status', user_status, nullable=False))
    op.add_column('user', sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_column('user', 'token')
    op.drop_column('user', 'status')
    op.add_column('otp', sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('otp', sa.Column('type', postgresql.ENUM('password_reset', 'email_verification', 'signup_confirmation', 'login_confirmation', name='otptype'), autoincrement=False, nullable=False))
    op.add_column('otp', sa.Column('code', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_otp_email_token'), table_name='otp')
    op.drop_column('otp', 'token_status')
    op.drop_column('otp', 'email_token')
    # Drop enum types if they exist
    email_token_status = sa.Enum('active', 'used', 'expired', name='emailtokenstatus')
    user_status = sa.Enum('active', 'inactive', 'banned', name='userstatus')
    email_token_status.drop(op.get_bind(), checkfirst=True)
    user_status.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
