"""migration-failed

Revision ID: d48192107d61
Revises: 0dcd3acf382f
Create Date: 2025-12-12 15:34:13.945725

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd48192107d61'
down_revision = '0dcd3acf382f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
