"""create a new table

Revision ID: e98732087769
Revises: c09c4a1bfec5
Create Date: 2025-12-22 16:42:32.197493

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e98732087769'
down_revision = 'c09c4a1bfec5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum types first (Postgres requires the type to exist before using it)
    auth_provider = sa.Enum('google', 'apple', name='authprovider')
    auth_provider.create(op.get_bind(), checkfirst=True)
    
    op.create_index(op.f('ix_otp_token_status'), 'otp', ['token_status'], unique=False)
    op.add_column('user', sa.Column('provider', auth_provider, nullable=True))
    op.add_column('user', sa.Column('provider_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_user_provider'), 'user', ['provider'], unique=False)
    op.create_index(op.f('ix_user_provider_id'), 'user', ['provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_provider_id'), table_name='user')
    op.drop_index(op.f('ix_user_provider'), table_name='user')
    op.drop_column('user', 'provider_id')
    op.drop_column('user', 'provider')
    op.drop_index(op.f('ix_otp_token_status'), table_name='otp')
    # Drop enum types if they exist
    auth_provider = sa.Enum('google', 'apple', name='authprovider')
    auth_provider.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
